version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /apps/autotests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /docker/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /docker/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
