/**
 * Invitations CRUD (Фаза 4.3). protocol_id, code, max_runs, expires_at. Публичный GET по коду для участника.
 * Файл новый — исходные не удаляем.
 */
const express = require('express');
const { body, param, query, validationResult } = require('express-validator');
const { pool } = require('../db');
const {
  requireAuth,
  requireRole,
  requireOperation,
  OPERATIONS,
  isPlatformAdmin,
  hasProtocolMembership,
} = require('../middleware/auth');
const { issueIngestToken } = require('../security/ingest-token');
const {
  findInvitationByCode,
  reserveInvitationRun,
} = require('../ingest/invitation-repository');
const { withTransaction, lockSessionKey } = require('../db/transaction');
const {
  resolveReadableServerOwnedUploadPath,
  getStoredContentPath,
  safeDownloadName,
} = require('../security/upload-paths');
const { INLINE_MEDIA_TYPES } = require('../security/stimulus-files');
const config = require('../config');
const crypto = require('crypto');
const path = require('path');
const { normalizeMandatoryParticipantShell } = require('../protocol/participant-shell');

const router = express.Router();
const stimuliUploadsRoot = path.join(config.storage.uploadsRoot, 'stimuli');

function hasGlobalInvitationAccess(user) {
  return isPlatformAdmin(user);
}

/** Invitation codes are bearer secrets and must be generated by the server. */
function generateCode() {
  return crypto.randomBytes(16).toString('base64url');
}

async function resolveInvitationByCode(code, queryable = pool) {
  const row = await findInvitationByCode(queryable, code);
  return row ? { row, resolvedVia: 'invitation_code' } : null;
}

function referencedStimulusIds(definition) {
  const ids = new Set();
  const add = value => {
    const normalized = String(value ?? '').replace(/^api:/, '');
    if (/^[1-9]\d*$/.test(normalized)) ids.add(Number(normalized));
  };
  const addTrials = trials => {
    if (!Array.isArray(trials)) return;
    trials.forEach(trial => add(trial?.stimulusId ?? trial?.stimulus_id));
  };
  const blocks = Array.isArray(definition?.blocks) ? definition.blocks : [];
  blocks.forEach(block => {
    const params = block?.params || {};
    const stimulusIds = Array.isArray(params.stimuli_ids) ? params.stimuli_ids : [];
    stimulusIds.forEach(add);
    add(params.stimulus_id);
    addTrials(params.trials);
    addTrials(block?.trials);
    addTrials(block?.content?.trials);
  });
  return [...ids].filter(Number.isSafeInteger);
}

function publicStimulusMetadata(metadata) {
  if (!metadata || typeof metadata !== 'object' || Array.isArray(metadata)) return {};
  const result = {};
  for (const key of ['text', 'label', 'emotion', 'alt']) {
    if (typeof metadata[key] === 'string') result[key] = metadata[key].slice(0, 512);
  }
  return result;
}

async function resolveActiveParticipantInvitation(req, res) {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    res.status(400).json({ errors: errors.array() });
    return null;
  }
  const resolved = await resolveInvitationByCode(req.params.code.trim());
  if (!resolved) {
    res.status(404).json({ error: 'Invitation not found' });
    return null;
  }
  if (resolved.row.expires_at && new Date(resolved.row.expires_at) < new Date()) {
    res.status(410).json({ error: 'Invitation expired' });
    return null;
  }
  return resolved.row;
}

/**
 * GET /invitations/by-code/:code — публичный: по коду вернуть протокол для участника (без auth).
 * Проверка: срок действия, лимит прогонов (если задан).
 */
router.get(
  '/by-code/:code',
  [
    param('code').trim().notEmpty().isLength({ max: 64 }),
    query('session_id').optional().trim().notEmpty().isLength({ max: 64 }),
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) return res.status(400).json({ errors: errors.array() });
      const code = req.params.code.trim();
      const resolved = await resolveInvitationByCode(code);
      if (!resolved) {
        return res.status(404).json({ error: 'Invitation not found' });
      }
      const inv = resolved.row;
      if (inv.expires_at && new Date(inv.expires_at) < new Date()) {
        return res.status(410).json({ error: 'Invitation expired' });
      }
      if (inv.max_runs != null && inv.used_runs >= inv.max_runs) {
        const sessionId = req.query.session_id ? String(req.query.session_id) : null;
        let alreadyAdmitted = false;
        if (sessionId) {
          const bound = await pool.query(
            `SELECT 1
             FROM sessions
             WHERE session_id = $1
               AND invitation_id = $2
               AND project_id = $3
               AND protocol_id = $4`,
            [sessionId, inv.id, inv.project_id, inv.protocol_id]
          );
          alreadyAdmitted = Boolean(bound.rows[0]);
        }
        if (!alreadyAdmitted) {
          return res.status(410).json({ error: 'Invitation run limit reached' });
        }
      }
      res.json({
        invitation_id: inv.id,
        code: inv.code,
        protocol_id: inv.protocol_id,
        protocol_name: inv.protocol_name,
        project_id: inv.project_id,
        max_runs: inv.max_runs,
        used_runs: inv.used_runs,
        expires_at: inv.expires_at,
        definition: normalizeMandatoryParticipantShell(inv.protocol_definition),
        source: {
          type: 'invitation_code',
          value: inv.code,
        },
      });
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: 'Server error' });
    }
  }
);

router.get(
  '/by-code/:code/stimuli',
  [param('code').trim().notEmpty().isLength({ max: 64 })],
  async (req, res) => {
    try {
      const invitation = await resolveActiveParticipantInvitation(req, res);
      if (!invitation) return;
      const referencedIds = referencedStimulusIds(invitation.protocol_definition);
      if (!referencedIds.length) return res.json([]);
      const result = await pool.query(
        `SELECT id, project_id, name, mime_type, size_bytes, metadata
         FROM stimuli
         WHERE project_id = $1 AND id = ANY($2::int[])
         ORDER BY id`,
        [invitation.project_id, referencedIds]
      );
      return res.json(result.rows.map(row => {
        const metadata = publicStimulusMetadata(row.metadata);
        return {
          id: row.id,
          name: row.name,
          mime_type: row.mime_type,
          size_bytes: row.size_bytes,
          metadata,
          content_url: getStoredContentPath(row.metadata)
            ? `/invitations/by-code/${encodeURIComponent(invitation.code)}/stimuli/${row.id}/content`
            : null,
        };
      }));
    } catch (err) {
      console.error(err);
      return res.status(500).json({ error: 'Failed to load participant stimuli' });
    }
  }
);

router.get(
  '/by-code/:code/stimuli/:stimulusId/content',
  [
    param('code').trim().notEmpty().isLength({ max: 64 }),
    param('stimulusId').isInt({ min: 1 }),
  ],
  async (req, res) => {
    try {
      const invitation = await resolveActiveParticipantInvitation(req, res);
      if (!invitation) return;
      const stimulusId = Number(req.params.stimulusId);
      if (!referencedStimulusIds(invitation.protocol_definition).includes(stimulusId)) {
        return res.status(404).json({ error: 'Stimulus not found' });
      }
      const result = await pool.query(
        `SELECT id, name, mime_type, metadata
         FROM stimuli
         WHERE id = $1 AND project_id = $2`,
        [stimulusId, invitation.project_id]
      );
      const stimulus = result.rows[0];
      if (!stimulus) return res.status(404).json({ error: 'Stimulus not found' });
      const resolved = await resolveReadableServerOwnedUploadPath(
        stimuliUploadsRoot,
        getStoredContentPath(stimulus.metadata)
      );
      if (!resolved.ok) {
        const status = resolved.code === 'content_file_missing' ? 404 : 422;
        return res.status(status).json({
          error: 'Stimulus binary is unavailable',
          code: resolved.code,
        });
      }
      const mimeType = String(stimulus.mime_type || '').toLowerCase();
      res.setHeader('Content-Type', mimeType || 'application/octet-stream');
      res.setHeader(
        'Content-Disposition',
        `${INLINE_MEDIA_TYPES.has(mimeType) ? 'inline' : 'attachment'}; filename="${safeDownloadName(stimulus.name)}"`
      );
      return res.sendFile(resolved.absolutePath);
    } catch (err) {
      console.error(err);
      return res.status(500).json({ error: 'Failed to serve participant stimulus' });
    }
  }
);

/**
 * Public participant exchange: invitation code + client session id ->
 * short-lived server-issued token bound to both values.
 */
router.post(
  '/by-code/:code/ingest-token',
  [
    param('code').trim().notEmpty().isLength({ max: 64 }),
    body('session_id').trim().notEmpty().isLength({ max: 64 }),
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) {
        return res.status(400).json({ errors: errors.array() });
      }
      const code = req.params.code.trim();
      const sessionId = String(req.body.session_id);
      const admission = await withTransaction(pool, async client => {
        await lockSessionKey(client, sessionId);
        const invitation = await findInvitationByCode(client, code, { forUpdate: true });
        if (!invitation) {
          const error = new Error('Invitation not found');
          error.status = 404;
          error.code = 'invitation_not_found';
          throw error;
        }
        if (invitation.expires_at && new Date(invitation.expires_at) < new Date()) {
          const error = new Error('Invitation expired');
          error.status = 410;
          error.code = 'invitation_expired';
          throw error;
        }

        const existing = await client.query(
          `SELECT invitation_id, project_id, protocol_id
           FROM sessions
           WHERE session_id = $1
           FOR UPDATE`,
          [sessionId]
        );
        const boundSession = existing.rows[0] || null;
        if (
          boundSession
          && (
            Number(boundSession.invitation_id) !== Number(invitation.id)
            || Number(boundSession.project_id) !== Number(invitation.project_id)
            || Number(boundSession.protocol_id) !== Number(invitation.protocol_id)
          )
        ) {
          const error = new Error('Session is already bound to another invitation');
          error.status = 409;
          error.code = 'session_invitation_mismatch';
          throw error;
        }

        let created = false;
        if (!boundSession) {
          const reserved = await reserveInvitationRun(client, invitation.id);
          if (!reserved) {
            const error = new Error('Invitation run limit reached');
            error.status = 410;
            error.code = 'invitation_run_limit';
            throw error;
          }
          await client.query(
            `INSERT INTO sessions (
               session_id, project_id, protocol_id, invitation_id, started_at
             ) VALUES ($1, $2, $3, $4, current_timestamp)`,
            [sessionId, invitation.project_id, invitation.protocol_id, invitation.id]
          );
          created = true;
        }
        return { invitation, created };
      });

      const token = issueIngestToken({
        sessionId,
        invitation: admission.invitation,
      });
      return res.json({
        token,
        token_type: 'Bearer',
        scope: 'participant:ingest',
        session_id: sessionId,
        invitation_code: admission.invitation.code,
        admitted: true,
        session_created: admission.created,
      });
    } catch (err) {
      if (err.status) {
        return res.status(err.status).json({
          error: err.message,
          ...(err.code ? { code: err.code } : {}),
        });
      }
      if (err.code === '23505') {
        return res.status(409).json({
          error: 'Session admission conflicted with another request',
          code: 'session_admission_conflict',
        });
      }
      console.error(err);
      return res.status(500).json({ error: 'Failed to issue ingest token' });
    }
  }
);

/** Все остальные маршруты — с авторизацией */
router.use(requireAuth);

router.get(
  '/',
  requireRole('admin', 'PI', 'researcher', 'analyst', 'assistant', 'developer'),
  requireOperation(OPERATIONS.INVITATION_READ),
  [query('protocol_id').optional().isInt()],
  async (req, res) => {
    try {
      const globalAccess = hasGlobalInvitationAccess(req.user);
      let sql = `
        SELECT i.id, i.protocol_id, i.code, i.max_runs, i.used_runs AS runs_used,
               i.expires_at, i.created_at, pr.name AS protocol_name
        FROM invitations i
        INNER JOIN protocols pr ON pr.id = i.protocol_id
        INNER JOIN projects p ON p.id = pr.project_id
      `;
      if (!globalAccess) {
        sql += `
          INNER JOIN user_organizations uo ON uo.organization_id = p.organization_id
          INNER JOIN user_projects up ON up.project_id = p.id AND up.user_id = uo.user_id
        `;
      }
      sql += globalAccess ? ' WHERE 1=1' : ' WHERE uo.user_id = $1';
      const params = globalAccess ? [] : [req.user.sub];
      if (req.query.protocol_id) {
        params.push(req.query.protocol_id);
        sql += ` AND i.protocol_id = $${params.length}`;
      }
      sql += ' ORDER BY i.created_at DESC';
      const r = await pool.query(sql, params);
      res.json(r.rows);
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: 'Server error' });
    }
  }
);

router.post(
  '/',
  requireRole('admin', 'PI', 'researcher', 'analyst', 'assistant', 'developer'),
  requireOperation(OPERATIONS.INVITATION_WRITE),
  requireOperation(OPERATIONS.PROTOCOL_PUBLISH),
  [
    body('protocol_id').isInt(),
    body('max_runs').optional().isInt({ min: 1 }),
    body('expires_at').optional().isISO8601(),
  ],
  async (req, res) => {
    try {
      const errors = validationResult(req);
      if (!errors.isEmpty()) return res.status(400).json({ errors: errors.array() });
      if (Object.prototype.hasOwnProperty.call(req.body || {}, 'code')) {
        return res.status(400).json({
          error: 'Invitation codes are generated by the server',
          code: 'server_generated_invitation_code_required',
        });
      }
      const { protocol_id, max_runs, expires_at } = req.body;
      const protocolAllowed = await hasProtocolMembership(pool, protocol_id, req.user);
      if (!protocolAllowed) return res.status(403).json({ error: 'Protocol not found or access denied' });
      let code = generateCode();
      let exists = await pool.query('SELECT 1 FROM invitations WHERE code = $1', [code]);
      while (exists.rows[0]) {
        code = generateCode();
        exists = await pool.query('SELECT 1 FROM invitations WHERE code = $1', [code]);
      }
      const r = await pool.query(
        `INSERT INTO invitations (protocol_id, code, max_runs, expires_at)
         VALUES ($1, $2, $3, $4)
         RETURNING id, protocol_id, code, max_runs, used_runs, expires_at, created_at`,
        [protocol_id, code, max_runs || null, expires_at || null]
      );
      res.status(201).json(r.rows[0]);
    } catch (err) {
      if (err.code === '23503') return res.status(400).json({ error: 'Protocol not found' });
      if (err.code === '23505') return res.status(409).json({ error: 'Invitation code already exists' });
      console.error(err);
      res.status(500).json({ error: 'Create failed' });
    }
  }
);

router.get(
  '/:id',
  requireRole('admin', 'PI', 'researcher', 'analyst', 'assistant', 'developer'),
  requireOperation(OPERATIONS.INVITATION_READ),
  [param('id').isInt()],
  async (req, res) => {
    try {
      const globalAccess = hasGlobalInvitationAccess(req.user);
      const r = globalAccess
        ? await pool.query(
          `SELECT i.id, i.protocol_id, i.code, i.max_runs, i.used_runs AS runs_used,
                  i.expires_at, i.created_at, pr.name AS protocol_name
           FROM invitations i
           INNER JOIN protocols pr ON pr.id = i.protocol_id
           WHERE i.id = $1`,
          [req.params.id]
        )
        : await pool.query(
          `SELECT i.id, i.protocol_id, i.code, i.max_runs, i.used_runs AS runs_used,
                  i.expires_at, i.created_at, pr.name AS protocol_name
           FROM invitations i
           INNER JOIN protocols pr ON pr.id = i.protocol_id
           INNER JOIN projects p ON p.id = pr.project_id
           INNER JOIN user_organizations uo ON uo.organization_id = p.organization_id
           INNER JOIN user_projects up ON up.project_id = p.id AND up.user_id = uo.user_id
           WHERE i.id = $1 AND uo.user_id = $2`,
          [req.params.id, req.user.sub]
        );
      if (!r.rows[0]) return res.status(404).json({ error: 'Not found' });
      res.json(r.rows[0]);
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: 'Server error' });
    }
  }
);

router.delete(
  '/:id',
  requireRole('admin', 'PI', 'researcher', 'developer'),
  requireOperation(OPERATIONS.INVITATION_WRITE),
  [param('id').isInt()],
  async (req, res) => {
    try {
      const globalAccess = hasGlobalInvitationAccess(req.user);
      const r = globalAccess
        ? await pool.query(
          'DELETE FROM invitations WHERE id = $1 RETURNING id',
          [req.params.id]
        )
        : await pool.query(
          `DELETE FROM invitations i
           USING protocols pr, projects p, user_organizations uo
           WHERE i.protocol_id = pr.id AND pr.project_id = p.id AND p.organization_id = uo.organization_id AND uo.user_id = $1 AND i.id = $2
             AND EXISTS (
               SELECT 1 FROM user_projects up
               WHERE up.project_id = p.id AND up.user_id = uo.user_id
             )
           RETURNING i.id`,
          [req.user.sub, req.params.id]
        );
      if (!r.rows[0]) return res.status(404).json({ error: 'Not found' });
      res.status(204).send();
    } catch (err) {
      console.error(err);
      res.status(500).json({ error: 'Delete failed' });
    }
  }
);

module.exports = router;
module.exports.resolveInvitationByCode = resolveInvitationByCode;
module.exports.generateCode = generateCode;
module.exports.referencedStimulusIds = referencedStimulusIds;
module.exports.publicStimulusMetadata = publicStimulusMetadata;
